language: php

php:
    - 7.0

matrix:
    fast_finish: true

install:
    - composer install --prefer-source

after_script:
    - bash -c '[[ -f "build/clover.xml" ]] && wget https://scrutinizer-ci.com/ocular.phar'
    - bash -c '[[ -f "build/clover.xml" ]] && php ocular.phar code-coverage:upload --format=php-clover build/clover.xml'

sudo: false
